#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare resourcehacker for snap
#
# Date: Feb 17 2018
#

dlrh () {
    wget http://www.angusj.com/resourcehacker/resource_hacker.zip &> /dev/null
    for fnts in andalemo.ttf arialbd.ttf arialbi.ttf ariali.ttf arial.ttf ariblk.ttf comicbd.ttf comic.ttf courbd.ttf courbi.ttf couri.ttf cour.ttf georgiab.ttf georgiai.ttf georgia.ttf georgiaz.ttf impact.ttf l_10646.ttf lucon.ttf micross.ttf symbol.ttf tahomabd.ttf tahoma.ttf timesbd.ttf timesbi.ttf timesi.ttf times.ttf trebucbd.ttf trebucbi.ttf trebucit.ttf trebuc.ttf verdanab.ttf verdanai.ttf verdana.ttf verdanaz.ttf webdings.ttf wingding.ttf
    do
    wget https://github.com/caarlos0-graveyard/msfonts/blob/master/fonts/$fnts?raw=true -P share/wine/fonts &> /dev/null
    mv share/wine/fonts/$fnts?raw=true share/wine/fonts/$fnts
    done
}
mkrawpng () {
cat > rawpng <<'EOF'
iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAA
B3RJTUUH4AwVExIG91AzQQAADdJJREFUaN7VmmuMXdV1x39r7XPvzHg8ZmyPx45fmJgGaig0PAQl
cVAj2oQU0TShPEKlklKi1FIIbUBVU6F8idI2DQhFoSilTUpLSRAVfQAObSMggZaUuOBScAwY2xiM
Gb9mPOP7Omc/+mHvc++514Mdq+qHntHWXN2z99rr8V+PvfaF/+ePnOD78H+818nQn3e9DEyojsFN
qv9PZmNN9JR+xQTAp3Eixsv1JY3ueqlsUgNWAz+TJr0GzAGNtEl1Q18hcjxhFHgPcAVwCZABLwOP
ATsAm4Z/Fzol4+cBVyX+ZoCtwCPAkXKTDcD2AaYC0AT2AE8A3wZ+E1gFjAJDiSE9DvPrgQPz0O0A
HwVOSXSOR2MDcHQeGk8DK0gEXgDClz4+HmbuWRHeumMyPPX7S8O9v7EoXH3eSNiwvFZdeAC4HZhI
gtQH4FFqLgO+BIQHN02E8MCpIdy/Oux8eElJZ3OyzliaO4hxSaj4CyDs+OrKLo0rL+vyc5MAFwLP
ff4jp3DXDUthQSsuawMdBScgkfaDzze49o7D5QY/AG4CppJGq1AoN/8bRK4O3zkdJudgGHCBs286
yMvb3RbgmgSJBpAPwEiBhcDuNUtqi/fcvQZWNyPq1xXIqQcB/liBDwKR+fE2rEt6OQ0408NZDs6w
cKrlmg+OEv52DRefXQO4FHiUuGIkMVxaosTuqotPq0NwMA4YhaUwUteSwRpgODZwlBY4C1j8teuW
gC9gocAwFLaLuEyJegGtx028ghsYRmFUYY2HNZ5nv7iSTdeNArwP+Osk8nDFJ7rMnLduGEIAMdGS
XnCuT8v6Lsx3lXv1xjFY7iMvCIcPdQ0l/c5jkjJkYPg0RGBU4DTP3R9fxnVXjACcC3wzYbkUoqvR
wpfbJJ6MqSLl3fJQ+e6MrnIXaeLH8Obe7pzQk14zMNKzQGHi8Gm4UlkKdYHVgQdueA8XnF0H2Ah8
PkGp3g8LibRJtFGCPx7fXeYFWLB+sp6US9cC+/Z1FbCjZ4GqlkLGfuf4wj3TPPd6Dk0DNglSCjEs
sBJ+fNfaksIm4L0MhleRSFviOlcI3p1QgK51JhaWqMgijczw8iu2nNOuQCht4g1o4P6HW9x53ywX
XbsPuXQnu+ccTGdgtcdQTaAW+LuvTZK0/zsDVugpxUcfKNpCOIk87kNSgJZmELztKmB3TwBNMBEB
o7Q73TebgeK0j+zh4RdnYX8dvBJKLdaFT54zXs69CljeJ4D0wjAoNlfCiYqH3rM8at90fTCUAsUn
HGsBFNdRbNFV0z3A54DpT946xSM75uCdGnjFeiWowijcecsyiE688RgLiBISfWerAp0QQpOrl9ai
JayCV3wuzM52NVARQDOcVYq2YgvFW1O+KYDngN8GDl/5u3spFoE06hQNJW8JPijXXNa1wi8kAZLn
RvwW7QxXKEXTENxPj6Fz1o0C4GxG0VJaDcNLrxeQkmafE7tCsR2laAu+t0kOtIjlxm0Al/zWGzAz
jHdK4RRbCCNqGB1RiPVPLQnQdeKiA0VbcFZPxgI4H9fnHaKCc8FHH54C5ioCGIq2YJMQFUdxxFKh
CXwP+JctO5oUQwUjNUPRVPKO4nLh9FV16NU2ZfgABJsbinaymOtncoDpgZI+RAGaBlsIRUcIvWX9
FiiS9p0z+F6sDkmIglgh3QXwwGNz6GwdWwi+UIJXJsZqAGvpZdiuBWxH4+beoKrzMV2uMX0KUJOU
CzZXXN6fuLOqBfKGIiJY56PT9J5SCA/sBPJGYeq4GnnbEqzgCmH1khr0ymPpsqcZeVPJNNBsOvZM
dQYZz+il57OJNdAGYNL6qASbZ6iHogCfd+EdKgLEEIfEOOv7s2W12NoE1CfG60DA5oIJSmEDew+5
Y+aHFIWi5qDR8DSaAWJZboCfAy4GLkpjSW9XYf2KOgSPs4L1im0FfOX40GeBoiVIprgixHDXY6bU
0vXAzYhw9S+uYd+Bg7jCYJ0w17LMNGzpXL0wo1GWvAmqwmhmGBkWGu1wJvFktqqc+rELl3HtxmX8
+geWMjw6Dq4Ntsme/S0cigcKa5AK+T4L4JQQBF8Esp6Uhlhtfhq4ESA88mF8a46js4GsJmgQmg3Y
uqsJMEvlqCmaEk8Ra6hloxmNtgdYu3zpELd+Yi2fu3wlQwvGwDbBFzTncvYd3kfbBZwT4h9ITTHO
0ekl2aoAWRTAggTD8rF6+eZ+YBlQQ4Tw2EfBNtn9Zo6qQW3UxytvtrE2AGxL/uIiCmImDV7whWCN
suWPfp7zz14MZhhcm+Z0h7f2TZE78CEQBCSAiMaqxUuMBVZptxyvvt2e3weko3gDdaNctmEJV100
x+SKkZVrJoe5/P1LOXf9JP6dad6Y7kAwGA9DmWG2ZXngmYMlpX8jns4cEGLqN4g1SIB2I7BibIS9
u1tY2yQ6aYjMStJoSIIHCDZ0j3gqMbwnbLw2IECshYKLJdGKhUM8dPM5MG7AedyBgn3bDtDMPSKK
CtQzpWgF/vO1Bt/beghgGniGGHItgJpUyzghOMFLOjuG6BsqkVkBjEr0Ng/OB4SAaCVveAFvqnng
WB8QgeChaWFXow27Q6yj0p9RgwB1UYL17Jhq85lvbS+p3Jt8oDwjn1kyhFM0RAYlgBhBA6hCcIGg
gm17WoVntnAUNnBgpsO5p44xlAnWgwSBoi86DkCooC/NCxBUMK6yxEHNCIUL7Jhqc+U3/4tG7gB+
CDxILDs6CUK68axJOOzQlFcUMKoEF/Ah0GoFjrQtbx5q8/i2gzy9Y4afTDW62914ySr+/PqfZc9M
G1RRK1Tq8X4IideuObtfD5S+GkCNYeuuaX713q3l11uAPyCWG80kgACMZDXoZASnMb06ZbZwvDPb
4d93zfD97Qd5csfh6hY5sen1KvCh1SsXLtHxYeRQgXghBO1rKA5YIAlwnFpLRBgJhqu+/WL51d7E
fCMx307wMRAbEliQQtC6odG2bHpoG0/uOFQlOwU8mxTxHHAoujLf8SNmCUEhB8kELUwfP/1O7JN0
Sp8g3vcSRxDIc+EnX/gQp//JUxAT0W3A79GLPp6yFioECoM6AzkcbbqS+T3A48T+0itJ8zm9dqMC
3ucCeTqnB43hoWKBvmJOOoI4oeaVhZIxTsYohpo3GCuIjU5UtAMTtTrhKx9j7fgIwC8Tk5xJQ4lN
mqGQtIcV1Cm2I5i4/3PEduWLxOh1uDKOEPuyHgQKRWzkTXx/I6XvQEPIEKdkZGzedoCxL/8zf//S
ARYPDVELGRoM2Hgwb7RgpgHPf/bSksItwA3EU1mdWNMMrxpbCM0U/pzS6gTSUcMTHf4oMXLNps9N
eoEgYGOTAWvAZQklYR4BCkULxQRD3oKdh1sA3PgPL/Dph7aySIZYQIa66OzeCa2jniFnmL71V0hO
ezvxSFkKwfsnF+NbAXUahe91JHYnyLQTw+3EdJlDHKRisFDExZK99NNjBchNNFiueAvNdjd2vv3d
bW+x7s/+Fd9RFkkt4TlaYq4FJhieun4jxJPYV4HFpQC2A6GjUEgMgXl3x9LZS2ZL3+lvtTuBToSu
FNGnKnGy0pmzSrCKekka7r65Gfj+1NEWE19/FLFRCOMjJkMRaLU8H5ic4FMb1kLsld5MbK9EJ3Zx
Ltb0uhnHXnLMf1B2sSEmXgmFsMDUqEcS648RQEshir7WRxP4IvB1IIx94x9ZODTMqNSjWa1iczjS
cHzrwxeUaz4FnA7E01rRg49xfWHwxLc9PkIIq0gR17/3lLEueioQSg7ilRAMC7RbjS5KQtwNfANg
zT3/xKKRUUa0BiFi01ul2Q7cdt4Z5Zr4ob6A3ArilFpumM0dJ/V4AZfqNDJ8QbXUr1ggl+gghVIr
lMmh4fLNOBG5DeAO4JG3jra48K82s3jpKQy5DC1inC4KYf3oonJdVPUZE9hWQJzivfD2kW4p3Dmh
9gF1AlYxRRxYpZKWKgKEOgZFg8F4pW17zSOio+XE2LwJeGbL4Wn+8PEtTIwtpE5G5gzBwhuz3Tom
0u4oPggSYqKUXhJ6owKhdxXkSLMAsm41q0Ex1ejf/bT9CGMMkVlDuwM/fme6fHOQ6GRF0tpR4DPA
3q+88BLP7zzIAl8j73jenmlx32t7SALHOPzCNAtDneHcULNC3u5TzPGYD0D+7K59UB9mKGQM+Rqu
LexvtrpzFHgJ4PL7HuVAJ/BmI+eHU9N8d/cuiNjfSy/MWWL42wd8Fmifv3kzv/bk09z6/Itc8cQP
eLt5FGITbDvAlzf/iKy+gFYw7G8H7tv9Rhfd9N92zifAq1v27sdunyXTYeYK4b9n5nj+8DTExOch
3hQ+O6CRcvwlcCaxYbuAXr9mmJhpbyEeIWcr40fA5cD5xGQVLphYHq5cuz6cvmhxSXcnsX2yingP
ZgaYV2J75hNJceHSFavCL61cU+XtTuB9QozXE8CVxH5MeTnxOrETN5Ow30wwCmlOLa0dTQLV0roS
bjYJfzsxN5Tgf4cYDP6DWPMcTdCsFu7lLecw8eLkamBphcYTwJ8C0+VtYj0xUzJSnqPKvmgrfa7e
QpYdtCGqvdBeE8xVNFleApr0fZ4U0qCXkQdhpBW+RtP/8vqqhHKj7PmUzFRvDT29lmL3kD6gpWo7
sGxmVc2sFbrlrY2nF9XK8nm+G4P5lFRCrbRyLvMwUz3OnMjRyrXH+9FI5XLtGLpl/cNPsb5UUmll
Tyw0jlkw+Pxvf7HybgKezI9G5qMRgPA/JHEVLbrzwtsAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTYt
MTItMjJUMTk6NTE6MzQrMDU6MDCD1nJ8AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE2LTEyLTIyVDAw
OjE4OjA2KzA1OjAwvc1v3AAAAABJRU5ErkJggg==
EOF
}

mkrh () {
    7z x resource_hacker.zip -x'!changes.txt' -x'!ReadMe.txt' -o"usr/share/resourcehacker" &> /dev/null
    mv usr/share/resourcehacker/ResourceHacker.exe usr/share/resourcehacker/resourcehacker.exe
    find "usr" -type d -execdir chmod 755 {} +
    mkdir -p usr/share/pixmaps && mkdir -p usr/share/applications && mkdir bin
    base64 -d rawpng > usr/share/pixmaps/resourcehacker.png
}

mkdsk () {
ver=$(wget http://www.angusj.com/resourcehacker/ -q -S -O - 2>&1 | grep Version | awk '{print $2}' | sed 's|</strong><br>||')
cat > resourcehacker.desktop <<'EOF1'
[Desktop Entry]
Name=Resource Hacker
GenericName=Resource Editor
Comment=Simple and free resource editing tool.
Encoding=UTF-8
Version=
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/resourcehacker.png
Exec=resourcehacker %F
StartupWMClass=resourcehacker.exe
Categories=Development
MimeType=
EOF1
sed -i -e 's|Version=|Version='"$ver"'|g' resourcehacker.desktop
}

dlrh
mkrawpng
mkrh
mkdsk
mv resourcehacker bin && mv resourcehacker.desktop usr/share/applications
rm resource_hac*.zip rawpng dl_rh